[package]
name = "ethereum-desktop-wallet-wallet"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ethereum-desktop-wallet-core = { workspace = true }
alloy-primitives = "1.6.1"
alloy-signer = { version = "2.3.0", features = ["eip712"] }
alloy-provider = "2.3.0"
alloy-transport = "2.3.0"
alloy-eips = "2.3.0"
alloy-sol-types = "1.6.1"
alloy-rpc-types-eth = "2.3.0"
alloy-network = "2.3.0"
alloy-consensus = "2.3.0"

[dev-dependencies]
alloy-signer-local = "2.3.0"
alloy-node-bindings = "2.3.0"
alloy-sol-types = { version = "1.6.1", features = ["json"] }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
alloy-contract = "2.3.0"


[lints]
workspace = true
