[package]
name = "ethereum-desktop-wallet-core"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-provider = { workspace = true }
inventory = "0.3.24"
serde = "1.0.229"

[lints]
workspace = true
