[workspace]
members = ["bin", "core", "wallet"]
resolver = "2"

[workspace.dependencies]
alloy-consensus = "2.3.0"
alloy-contract = "2.3.0"
alloy-eips = "2.3.0"
alloy-network = "2.3.0"
alloy-node-bindings = "2.3.0"
alloy-primitives = "1.6.1"
alloy-provider = "2.3.0"
alloy-rpc-types-eth = "2.3.0"
alloy-signer = "2.3.0"
alloy-signer-local = "2.3.0"
alloy-sol-types = "1.6.1"
alloy-transport = "2.3.0"
async-trait = "0.1"
ethereum-desktop-wallet-core = { path = "core" }
futures = "0.3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
unreachable = "deny"
unimplemented = "deny"
todo = "warn"
missing_errors_doc = "allow"
cast_possible_truncation = "allow"
