allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-panic-in-tests = true
source-item-ordering = ["module"]
module-item-order-groupings = [
    [
        "use",
        [
            "use",
        ],
    ],
    [
        "modules",
        [
            "extern_crate",
            "mod",
            "foreign_mod",
        ],
    ],
    [
        "macros",
        [
            "macro",
        ],
    ],
    [
        "global_asm",
        [
            "global_asm",
        ],
    ],
    [
        "consts",
        [
            "static",
            "const",
        ],
    ],
    [
        "type_aliases",
        [
            "ty_alias",
        ],
    ],
    [
        "traits",
        [
            "trait",
            "trait_alias",
        ],
    ],
    [
        "structs_and_enums",
        [
            "struct",
            "enum",
            "union",
        ],
    ],
    [
        "impls",
        [
            "impl",
        ],
    ],
    [
        "fns",
        [
            "fn",
        ],
    ],
]
